export const SENTIMENT_WEIGHTS = {
  POSITIVE_WORD: 1.2,
  NEGATIVE_WORD: -1.5,
  POSITIVE_ADJECTIVE: 1.5,
  NEGATIVE_ADJECTIVE: -2.0,
  NEGATIVE_CONTEXT: 1.8,
  IDIOM_POSITIVE: 2.0,
  IDIOM_NEGATIVE: -2.5,
  EMOJI_POSITIVE: 1.0,
  EMOJI_NEGATIVE: -1.2,
  SENTIMENT_THRESHOLD: {
    POSITIVE: 0.2,
    NEGATIVE: -0.15
  }
};