export const SENTIMENT_WEIGHTS = {
  POSITIVE_WORD: 1.2,
  NEGATIVE_WORD: -1.5,
  POSITIVE_ADJECTIVE: 1.5,
  NEGATIVE_ADJECTIVE: -2.0,
  SENTIMENT_THRESHOLD: {
    POSITIVE: 0.2,
    NEGATIVE: -0.15
  }
};